# -*- coding: utf-8 -*-
"""task_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12rT5lUXwgwh2xOJQhhTVx-2DgSLo2WFY
"""

# Завдання 2
def get_cats_info(path):
    try:
        with open(path, encoding="utf-8") as file:
            cats = []
            for line in file:
                lines = line.strip().split(",")
                if len(lines) == 3:
                    cats.append({
                        "id": lines[0],
                        "name": lines[1],
                        "age": lines[2]
                    })
        return cats
    except FileNotFoundError:
        return "Файл не знайдено"

print(get_cats_info("text.txt"))